config/routes.rb
Rails.application.routes.draw do
  resources :questions, only: [:index, :show, :new, :create] do
  	resource :qvote, only: [:create, :destroy]
  	resources :qcomments, only: [:create]
    resources :comments, module: :questions, only: [:create]
  end
  
  resources :answers, only: [:create] do
  	resource :avote, only: [:create, :destroy]
  	resources :acomments, only: [:create]
    resources :comments, module: :answers, only: [:create]
  end

  devise_for :users
  
  root to: 'questions#index'

end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  answertext  :text
#  question_id :integer
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  has_many :comments, as: :commentable
  has_many :avotes

  validates :answertext, presence: true

  def avoted_by?(user)
    	avotes.exists?(user: user)
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/avote.rb
# == Schema Information
#
# Table name: avotes
#
#  id         :integer          not null, primary key
#  answer_id  :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Avote < ApplicationRecord
  belongs_to :answer
  belongs_to :user
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  comment          :text
#  commentable_type :string
#  commentable_id   :integer
#  user_id          :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates :comment, presence: true
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Question < ApplicationRecord
  belongs_to :user

  has_many :qvotes
  has_many :answers
  has_many :comments, as: :commentable

  validates :title, :description, presence: true

  def qvoted_by?(user)
  	qvotes.exists?(user: user)
  end

  def self.search(search)
	  if search
	  	Question.where("title like ? OR description like ?", "%#{search}%", "%#{search}%").order(created_at: :desc)
	  else	
	  	Question.all.order(created_at: :desc)
	  end
  end
end

app/models/qvote.rb
# == Schema Information
#
# Table name: qvotes
#
#  id          :integer          not null, primary key
#  question_id :integer
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Qvote < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         password_length: 8..128

  has_many :questions
  has_many :qvotes
  has_many :answers
  has_many :qcomments
  has_many :avotes

  validates :email,  :uniqueness => true, :format => {:with => /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/}
end

app/controllers/answers/comments_controller.rb
class Answers::CommentsController < CommentsController
	before_action :set_commentable

	def set_commentable
		@commentable = Answer.find(params[:answer_id])
	end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	def create
		@answer = Answer.new(answer_params)

		if @answer.save
			redirect_to question_path(@answer.question_id)
		end

	end

	protected
	def answer_params
		params.require(:answer).permit(:answertext,:question_id,:user_id)
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/avotes_controller.rb
class AvotesController < ApplicationController

	def create
		answer = Answer.find(params[:answer_id])
		answer.avotes.create(user: current_user)

		redirect_to question_path(answer.question_id)
	end

	def destroy
		answer = Answer.find(params[:answer_id])
		answer.avotes.where(user: current_user).take.try(:destroy)

		redirect_to question_path(answer.question_id)
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create

		@comment = @commentable.comments.new comment_params
		@comment.user = current_user
		@comment.save
		
		redirect_to request.referrer

	end

	private
		def comment_params
			params.require(:comment).permit(:comment)
		end


end

app/controllers/questions/comments_controller.rb
class Questions::CommentsController < CommentsController
	before_action :set_commentable

	def set_commentable
		@commentable = Question.find(params[:question_id])
	end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def index
		@questions = Question.search(params[:search])
	end

	def show 
		@question = Question.find(params[:id])
	end

	def new
		if user_signed_in?
			@question = Question.new
		else
			redirect_to new_user_session_path, notice: "Debe estar registrado para poder incluir una pregunta"
		end
	end

	def create
		@question = Question.new(question_params)
		if @question.save
			redirect_to question_path(@question.id), notice: "La pregunta fue adicionada correctamente"
		else
			render :new
		end
	end

	protected
	def question_params
		params.require(:question).permit(:title,:description,:user_id)
	end

end

app/controllers/qvotes_controller.rb
class QvotesController < ApplicationController

	def create
		question = Question.find(params[:question_id])
		question.qvotes.create(user: current_user)

		#redirect_to question_path(question.id)
		redirect_to question_path(question.id)
	end

	def destroy
		question = Question.find(params[:question_id])
		question.qvotes.where(user: current_user).take.try(:destroy)

		redirect_to question_path(question.id)
	end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def markdown(text)
	    options = {
	      filter_html:     true,
	      hard_wrap:       true,
	      link_attributes: { rel: 'nofollow', target: "_blank" },
	      space_after_headers: true,
	      fenced_code_blocks: true
	    }

	    extensions = {
	      autolink:           true,
	      superscript:        true,
	      disable_indented_code_blocks: true
	    }

	    renderer = Redcarpet::Render::HTML.new(options)
	    markdown = Redcarpet::Markdown.new(renderer, extensions)

	    markdown.render(text).html_safe
	end

	def time_ago(created_time)
		mins = ((Time.now - created_time) / 60).to_i
		case
			when mins < 0 
				"EN EL FUTURO"
			when mins == 0 
				"un momento"
			when mins == 1 
				"1 minuto"
			when mins >  1 && mins < 60
				mins.to_s + " minutos"
			when mins >=  60 && mins < 120
				"alrededor de 1 hora"
			when mins >=  120 && mins < 1440
				(mins / 60).to_s + " horas"
			when mins >= 1440 && mins < 2880
				"1 día"
			when mins >= 2880
				(mins / (60 * 24)).to_s + " días"
		end
		
	end

end

app/helpers/avotes_helper.rb
module AvotesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/qvotes_helper.rb
module QvotesHelper
end

app/views/questions/index.html.erb
<div class="container">
	<div class="row pt-3 justify-content-between">
		<div class="col-sm-3">
			<h1>Preguntas</h1>
		</div>
		<div class="col-sm-3 align-self-end">
			<%= button_to "Hacer una Pregunta", new_question_path, class: "btn btn-primary", method: :get %>
		</div>
		</div>
	</div>
</div>
<div class="container">
	<div class="row pt-3">
			<table class="table">
				<% @questions.each do |q| %>
					<tr>
						<td class="text-center">
							<h4><%= q.qvotes.count %></h4>
							<p>Votos</p>
						</td>
						<td class="text-center">
							<h4><%= q.answers.count %></h4>
							<p>Respuesta(s)</p>
						</td>
						<td>
							<h4><%= link_to markdown(q.title), question_path(q.id), class: "titulo" %></h4>
							<p>Preguntó <%= q.user.email %> hace <%= time_ago(q.created_at) %></p>
						</td>
					</tr>
				<% end %>
			</table>
	</div>
</div>

app/views/questions/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3 mt-5">
      <h1>Hacer Pregunta</h1>

      <% if @question.errors.any? %>
        <div class="alert alert-danger">
          <ul>
          <% @question.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_for @question do |q| %>
        <div class="form-group">
          Título: <%= q.text_field :title, class: "form-control input-lg", placeholder: "Ingresa el título de la Pregunta" %>
        </div>
        <div class="form-group">
          Cuerpo: <%= q.text_area :description, rows: 10, class: "form-control input-lg", placeholder: "Ingresa el cuerpo de la Pregunta" %>
        </div>
        	<%= q.hidden_field :user_id, value: current_user.id %>
        <div>
          <%= q.submit "Hacer Pregunta", class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<!-- Título de la Pregunta -->
<div class="container">
	<div class="row pt-3">
		<h1><%= markdown(@question.title) %></h1>
	</div>
</div>

<!-- Votos y Descripción de la Pregunta -->
<div class="container">
	<div class="row">
		<div class="col-sm-1">
			<% if user_signed_in? %>
				<% if @question.qvoted_by? current_user %>
					<%= link_to question_qvote_path(@question.id), method: :delete do %>
						<span class="oi oi-caret-top votos"></span>
						<h4 class="votos"><%= @question.qvotes.count %></h4>	
					<% end %>
				<% else %>
					<%= link_to question_qvote_path(@question.id), method: :post do %>
						<span class="oi oi-caret-top"></span>
						<h4><%= @question.qvotes.count %></h4>	
					<% end %>
				<% end %>
			<% else %>
				<span class="oi oi-caret-top"></span>
				<h4><%= @question.qvotes.count %></h4>
			<% end %>
		</div>
		<div class="col-sm-11">
			<h6><%= markdown(@question.description) %></h6>
		</div>
	</div>
</div>


<!-- Comentarios de la Pregunta -->
<div class="container">
	<div class="row m-1">
		<div class="col-sm-10 offset-sm-1">
			<% @question.comments.each do |q| %>
				<h6 class="border border-right-0 border-left-0 border-bottom-0"><small><%= markdown(q.comment) %></small></h6>
			<% end %>
		</div>
	</div>
</div>

<!-- Input para adicionar comentarios a la Pregunta (solo si hay usuario logeado) -->
<% if user_signed_in? %>
	<div class="container">
		<div class="row m-1">
			<div class="col-sm-10 offset-sm-1">

				<%= form_for [@question, @question.comments.build] do |f| %>
					<div class="form-group">
			    		<%= f.text_area :comment, class: "form-control input-lg", placeholder: "Agrega un comentario a la Pregunta" %>
			    	</div>
				
				  	<div class="col-sm-1 offset-sm-10">
				  	  <%= f.submit "Comentar", class: "btn btn-primary" %>
				  	</div>
				<% end %>
			</div>
		</div>
	</div>
<% end %>


<!-- Número de Respuestas a la Pregunta -->
<div class="container">
	<div class="row pt-3">
		<h1><%= @question.answers.count %> Respuesta(s)</h1>
	</div>
</div>

<!-- Votos, texto y comentarios de las respuestas -->
<div class="container">
	<% @question.answers.each do |a| %>
		<div class="row mt-1">
			<div class="col-sm-1">
				<% if user_signed_in? %>
					<% if a.avoted_by? current_user %>
						<%= link_to answer_avote_path(a.id), method: :delete do %>
							<span class="oi oi-caret-top votos"></span>
							<h4 class="votos"><%= a.avotes.count %></h4>	
						<% end %>
					<% else %>
						<%= link_to answer_avote_path(a.id), method: :post do %>
							<span class="oi oi-caret-top"></span>
							<h4><%= a.avotes.count %></h4>	
						<% end %>
					<% end %>
				<% else %>
					<span class="oi oi-caret-top"></span>
					<h4><%= a.avotes.count %></h4>
				<% end %>
			</div>
			<div class="col-sm-11">
				<h6 class="border border-right-0 border-left-0 border-bottom-0"><%= markdown(a.answertext) %></h6>
			</div>
			<!-- Comentarios de la Respuesta -->
			<div class="col-sm-10 offset-sm-2">
				<% a.comments.each do |ac| %>
					<h6 class="border border-right-0 border-left-0 border-bottom-0"><small><%= markdown(ac.comment) %></small></h6>
				<% end %>
			</div>
			<!-- Input para adicionar comentarios a la Respuesta (solo si hay usuario logeado) -->
			<% if user_signed_in? %>
				<div class="container">
					<div class="row m-1">
						<div class="col-sm-9 offset-sm-2">
							<%= form_for [a, a.comments.build] do |f| %>
								<div class="form-group">
						    		<%= f.text_area :comment, class: "form-control input-lg", placeholder: "Agrega un comentario a la Respuesta" %>
						    	</div>
							
							  	<div class="col-sm-1 offset-sm-10">
							  	  <%= f.submit "Comentar", class: "btn btn-primary" %>
							  	</div>
							<% end %>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	<% end %>		
</div>

<!-- Input para adicionar una Respuesta (solo si hay usuario logeado) -->
<% if user_signed_in? %>
	<div class="container">
		<div class="row pt-3">
			<h1>Tu Respuesta</h1>
		</div>
	</div>

	<div class="container">
		<div class="row m-1">
			<div class="col-sm-10 offset-sm-1">
				<%= form_for :answer, :url => answers_path do |a| %>
					<div class="form-group">
			    		<%= a.text_area :answertext, class: "form-control input-lg", placeholder: "Agrega tu respuesta" %>
			    	</div>
					<%= a.hidden_field :user_id, value: current_user.id %>
					<%= a.hidden_field :question_id, value: @question.id %>
				  	<div class="col-sm-1 offset-sm-10">
				  	  <%= a.submit "Agregar", class: "btn btn-primary" %>
				  	</div>
				<% end %>
			</div>
		</div>
	</div>
<% end %>