config/routes.rb
Rails.application.routes.draw do
  resources :questions, only: [:index, :show, :new, :create] do
  	resource :qvote, only: [:create, :destroy]
  	resources :qcomments, only: [:create]
    resources :comments, module: :questions, only: [:create]
  end
  
  resources :answers, only: [:create] do
  	resource :avote, only: [:create, :destroy]
  	resources :acomments, only: [:create]
    resources :comments, module: :answers, only: [:create]
  end

  devise_for :users
  
  root to: 'questions#index'

end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  answertext  :text
#  question_id :integer
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  has_many :comments, as: :commentable
  has_many :avotes

  validates :answertext, presence: true

  def avoted_by?(user)
    	avotes.exists?(user: user)
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/avote.rb
# == Schema Information
#
# Table name: avotes
#
#  id         :integer          not null, primary key
#  answer_id  :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Avote < ApplicationRecord
  belongs_to :answer
  belongs_to :user
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  comment          :text
#  commentable_type :string
#  commentable_id   :integer
#  user_id          :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates :comment, presence: true
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Question < ApplicationRecord
  belongs_to :user

  has_many :qvotes
  has_many :answers
  has_many :comments, as: :commentable

  validates :title, :description, presence: true

  def qvoted_by?(user)
  	qvotes.exists?(user: user)
  end

  def self.search(search)
	  if search
	  	Question.where("title like ? OR description like ?", "%#{search}%", "%#{search}%").order(created_at: :desc)
	  else	
	  	Question.all.order(created_at: :desc)
	  end
  end
end

app/models/qvote.rb
# == Schema Information
#
# Table name: qvotes
#
#  id          :integer          not null, primary key
#  question_id :integer
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Qvote < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         password_length: 8..128

  has_many :questions
  has_many :qvotes
  has_many :answers
  has_many :qcomments
  has_many :avotes

  validates :email,  :uniqueness => true, :format => {:with => /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/}
end

app/controllers/answers/comments_controller.rb
class Answers::CommentsController < CommentsController
	before_action :set_commentable

	def set_commentable
		@commentable = Answer.find(params[:answer_id])
	end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	def create
		@answer = Answer.new(answer_params)

		if @answer.save
			redirect_to question_path(@answer.question_id)
		end

	end

	protected
	def answer_params
		params.require(:answer).permit(:answertext,:question_id,:user_id)
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/avotes_controller.rb
class AvotesController < ApplicationController

	def create
		answer = Answer.find(params[:answer_id])
		answer.avotes.create(user: current_user)

		redirect_to question_path(answer.question_id)
	end

	def destroy
		answer = Answer.find(params[:answer_id])
		answer.avotes.where(user: current_user).take.try(:destroy)

		redirect_to question_path(answer.question_id)
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create

		@comment = @commentable.comments.new comment_params
		@comment.user = current_user
		@comment.save
		
		redirect_to request.referrer

	end

	private
		def comment_params
			params.require(:comment).permit(:comment)
		end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def index
		@questions = Question.search(params[:search])
	end

	def show 
		@question = Question.find(params[:id])
	end

	def new
		if user_signed_in?
			@question = Question.new
		else
			redirect_to new_user_session_path, notice: "Debe estar registrado para poder incluir una pregunta"
		end
	end

	def create
		@question = Question.new(question_params)
		if @question.save
			redirect_to question_path(@question.id), notice: "La pregunta fue adicionada correctamente"
		else
			render :new
		end
	end

	protected
	def question_params
		params.require(:question).permit(:title,:description,:user_id)
	end

end

app/controllers/qvotes_controller.rb
class QvotesController < ApplicationController

	def create
		question = Question.find(params[:question_id])
		question.qvotes.create(user: current_user)

		#redirect_to question_path(question.id)
		redirect_to question_path(question.id)
	end

	def destroy
		question = Question.find(params[:question_id])
		question.qvotes.where(user: current_user).take.try(:destroy)

		redirect_to question_path(question.id)
	end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def markdown(text)
	    options = {
	      filter_html:     true,
	      hard_wrap:       true,
	      link_attributes: { rel: 'nofollow', target: "_blank" },
	      space_after_headers: true,
	      fenced_code_blocks: true
	    }

	    extensions = {
	      autolink:           true,
	      superscript:        true,
	      disable_indented_code_blocks: true
	    }

	    renderer = Redcarpet::Render::HTML.new(options)
	    markdown = Redcarpet::Markdown.new(renderer, extensions)

	    markdown.render(text).html_safe
	end

	def time_ago(created_time)
		mins = ((Time.now - created_time) / 60).to_i
		case
			when mins < 0 
				"EN EL FUTURO"
			when mins == 0 
				"un momento"
			when mins == 1 
				"1 minuto"
			when mins >  1 && mins < 60
				mins.to_s + " minutos"
			when mins >=  60 && mins < 120
				"alrededor de 1 hora"
			when mins >=  120 && mins < 1440
				(mins / 60).to_s + " horas"
			when mins >= 1440 && mins < 2880
				"1 día"
			when mins >= 2880
				(mins / (60 * 24)).to_s + " días"
		end
		
	end

end

app/helpers/avotes_helper.rb
module AvotesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/qvotes_helper.rb
module QvotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous" />

    <title>FlowOverstack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

  	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  	  <a class="navbar-brand" href="/">FlowOverStack</a>
  	  
  	  <div class="container-fluid d-flex justify-content-end">
  	    <% if user_signed_in? %>
	  		  <span class="navbar-nav" href="#"><strong>Usuario actual: <%= current_user.email %></strong></span>
	  		<% end %>
	  		
  	    <ul class="navbar-nav">
  	    	<% if user_signed_in? %>
  	    		<li class="nav-item active"><a href="#"><%= link_to "Salir", destroy_user_session_path, method: :delete, class: "nav-link" %></a></li>
  	    	<% else %>
  	    		<li class="nav-item active"><a href="#"><%= link_to "Ingresar", new_user_session_path, class: "nav-link" %></a></li>
  	    	    <li class="nav-item active"><a href="#"><%= link_to "Registrarse", new_user_registration_path, class: "nav-link" %></a></li>
  	    	<% end %>	
  	    </ul>
        <%= form_tag questions_path, :method => 'get' do %>
          <%= text_field_tag :search, params[:search]? params[:search] : nil, placeholder: "Buscar preguntas" %>
        <% end %>
  	  </div>
  	</nav>  

  	<% if flash[:notice] %>
  		<p class="notice"><%= flash[:notice] %></p>
  	<% end %>
    
	<% if flash[:alert] %>
  		<p class="alert alert-info"><%= alert %></p>
  	<% end %>

    <%= yield %>
  </body>
</html>